@startuml
start
:открой на смартфоне 2гис;
:найди булочную;
:войди в булочную;
:спроси есть ли в продаже свежие круассаны;
if (ответ?) then (да)
:изрыгни проклюятье;
else (нет)
:купи круассан;
endif
:выйди из булочной;
:дойди до дома;
:войди в дом;
:ляг спать;
end
@enduml
